### ISSUE TITLE
Make thunk a library

### ISSUE THREAD

**Issue by felixmaker** [felixmaker/thunk#9]
Currently, thunk is used as a helper tool to build program. I am considering making it a library. One can simply add thunk as a dependency or a build dependency. I preper to achieve it as a build-dependency. I will show how to achieve them both.

If make thunk a dependency, one can simply add thunk into dependencies with some features to control which platform to support. So, the `Cargo.toml` file looks like:

```toml
[dependencies]
thunk-rs = {version="0.3", features=["xp"]}
```

But the above solution makes someone confused, because we do not use thunk in coding at all.

If make thunk a build dependency, it would be clear to control which version of VC-LTL or YY-Thunk to use. So, the Cargo.toml file looks like:

```toml
[build-dependencies]
thunks-rs = "0.3"
``` 

And one needs to create a `build.rs` file near the cargo manifest file, it may looks like:

```rust
use thunk::ThunkBuilder;
fn main() {
    ThunkBuilder::default().build();
}
```

Then, build the project and you will get an executable works on old windows platform.
